INSERT INTO `Societe` (`IdSociete`, `Name`, `Description`) VALUES
(1, 'DACCOR', 'Daccor est le 1er groupe hôtelier européen. '),
(2, 'HAIR LIQUIDE', 'Hair Liquide figure parmi les leaders mondiaux de la production de gaz industriels et médicaux.'),
(3, 'FLAIRBUS GROUP', 'Flairbus Group (ex EADS) est le n° 1 européen et le n° 2 mondial de l''industrie aéronautique, spatiale et de la défense.'),
(4, 'FLALCATEL LUCENT', 'Flalcatel-Lucent propose des solutions qui permettent aux fournisseurs de services, aux entreprises et aux administrations du monde entier d''offrir des services voix, données et vidéo à leurs propres clients.'),
(5, 'TALSTOM', 'Talstom figure parmi les principaux fabricants mondiaux d''infrastructures destinées aux secteurs de l''énergie et du transport.'),
(9, 'TARCELLORMITTAL', 'TArcelorMittal est le n° 1 mondial de la sidérurgie'),
(10, 'XAXA', 'Taxa est le 1er groupe d''assurance européen.'),
(11, 'BNPS PARIBAS', 'BNPS Paribas est le 1er groupe bancaire français. '),
(12, 'DACCORD', 'Daccor est le 1er groupe hôtelier européen.'),
(13, 'BOUYGUESOU', 'Bouyguesou est un groupe industriel diversifié organisé autour de 2 pôles d''activités.'),
(14, 'CAP HORN GEMINI', 'Cap horn gemini figure parmi les principaux prestataires mondiaux de services informatiques.'),
(15, 'AU CARREFOUR', 'Au Carrefour est le n° 1 européen et le n° 2 mondial de la grande distribution. '),
(16, 'CREDIT & AGRICOLE', 'Crédit & Agricole figure parmi les 1ers groupes bancaires européens.'),
(17, 'DANONOU', 'Danone figure parmi les 1ers groupes agroalimentaires mondiaux.'),
(18, 'FEDF', 'Electricité de France (FEDF) est le n° 1 français de la production, de la commercialisation et de la distribution d''électricité.');