package fr.dauphine.etrade.model;
// default package
// Generated 19 mars 2015 01:35:34 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enchere generated by hbm2java
 */
@Entity
@Table(name = "Enchere")
public class Enchere implements java.io.Serializable {

	/**
	 * Default serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private Long idEnchere;
	private Ordre ordre;
	private Portefeuille portefeuille;
	private boolean main;
	private BigDecimal prix;
	private Date dateDebut;
	private Date dateFin;

	public Enchere() {
	}

	public Enchere(Ordre ordre, Portefeuille portefeuille, boolean main,
			BigDecimal prix, Date dateDebut, Date dateFin) {
		this.ordre = ordre;
		this.portefeuille = portefeuille;
		this.main = main;
		this.prix = prix;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdEnchere", unique = true, nullable = false)
	public Long getIdEnchere() {
		return this.idEnchere;
	}

	public void setIdEnchere(Long idEnchere) {
		this.idEnchere = idEnchere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdOrder", nullable = false)
	public Ordre getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Ordre ordre) {
		this.ordre = ordre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPortefeuille", nullable = false)
	public Portefeuille getPortefeuille() {
		return this.portefeuille;
	}

	public void setPortefeuille(Portefeuille portefeuille) {
		this.portefeuille = portefeuille;
	}

	@Column(name = "Main", nullable = false)
	public boolean isMain() {
		return this.main;
	}

	public void setMain(boolean main) {
		this.main = main;
	}

	@Column(name = "Prix", nullable = false, precision = 10)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_Debut", nullable = false, length = 19, columnDefinition = "DEFAULT CURRENT_TIMESTAMP")
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_Fin", nullable = false, length = 19)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
