package fr.dauphine.etrade.model;

// default package
// Generated 5 mars 2015 14:47:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actualite generated by hbm2java
 */
@Entity
@Table(name = "Actualite", catalog = "etrade_titres")
public class Actualite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idActualite;
	private Societe societe;
	private Utilisateur utilisateur;
	private String file;

	public Actualite() {
	}

	public Actualite(Societe societe, Utilisateur utilisateur, String file) {
		this.societe = societe;
		this.utilisateur = utilisateur;
		this.file = file;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdActualite", unique = true, nullable = false)
	public Long getIdActualite() {
		return this.idActualite;
	}

	public void setIdActualite(Long idActualite) {
		this.idActualite = idActualite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSociete", nullable = false)
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdUtilisateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "File", nullable = false, length = 200)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

}
