package fr.dauphine.etrade.model;

// default package
// Generated 5 mars 2015 14:47:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "Transaction", catalog = "etrade_titres")
public class Transaction implements java.io.Serializable {

	private Long idTransaction;
	private Ordre ordreByIdOrderAchat;
	private Ordre ordreByIdOrderVente;
	private BigDecimal prix;
	private int quantite;
	private Date date;

	public Transaction() {
	}

	public Transaction(Ordre ordreByIdOrderAchat, Ordre ordreByIdOrderVente,
			BigDecimal prix, int quantite, Date date) {
		this.ordreByIdOrderAchat = ordreByIdOrderAchat;
		this.ordreByIdOrderVente = ordreByIdOrderVente;
		this.prix = prix;
		this.quantite = quantite;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdTransaction", unique = true, nullable = false)
	public Long getIdTransaction() {
		return this.idTransaction;
	}

	public void setIdTransaction(Long idTransaction) {
		this.idTransaction = idTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdOrderAchat", nullable = false)
	public Ordre getOrdreByIdOrderAchat() {
		return this.ordreByIdOrderAchat;
	}

	public void setOrdreByIdOrderAchat(Ordre ordreByIdOrderAchat) {
		this.ordreByIdOrderAchat = ordreByIdOrderAchat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdOrderVente", nullable = false)
	public Ordre getOrdreByIdOrderVente() {
		return this.ordreByIdOrderVente;
	}

	public void setOrdreByIdOrderVente(Ordre ordreByIdOrderVente) {
		this.ordreByIdOrderVente = ordreByIdOrderVente;
	}

	@Column(name = "Prix", nullable = false, precision = 8)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	@Column(name = "Quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
