package fr.dauphine.etrade.model;

// default package
// Generated 11 mars 2015 16:13:53 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Portefeuille generated by hbm2java
 */
@Entity
@Table(name = "Portefeuille")
public class Portefeuille implements java.io.Serializable {

  /**
   * Default serialVersionUID
   */
  private static final long serialVersionUID = 1L;
  private long idPortefeuille;
  private String description;
  private Set<Ordre> ordres = new HashSet<Ordre>(0);
  private Set<TransactionBancaire> transactionBancaires = new HashSet<TransactionBancaire>(0);
  private Utilisateur utilisateur;

  public Portefeuille() {
  }

  public Portefeuille(long idPortefeuille) {
    this.idPortefeuille = idPortefeuille;
  }

  public Portefeuille(long idPortefeuille, String description, Set<Ordre> ordres,
      Set<TransactionBancaire> transactionBancaires, Utilisateur utilisateurs) {
    this.idPortefeuille = idPortefeuille;
    this.description = description;
    this.ordres = ordres;
    this.transactionBancaires = transactionBancaires;
    this.utilisateur = utilisateurs;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "IdPortefeuille", unique = true, nullable = false)
  public long getIdPortefeuille() {
    return this.idPortefeuille;
  }

  public void setIdPortefeuille(long idPortefeuille) {
    this.idPortefeuille = idPortefeuille;
  }

  @Column(name = "Description", length = 200)
  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "portefeuille")
  public Set<Ordre> getOrdres() {
    return this.ordres;
  }

  public void setOrdres(Set<Ordre> ordres) {
    this.ordres = ordres;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "portefeuille")
  public Set<TransactionBancaire> getTransactionBancaires() {
    return this.transactionBancaires;
  }

  public void setTransactionBancaires(Set<TransactionBancaire> transactionBancaires) {
    this.transactionBancaires = transactionBancaires;
  }

  @OneToOne(mappedBy = "portefeuille")
  public Utilisateur getUtilisateur() {
    return this.utilisateur;
  }

  public void setUtilisateur(Utilisateur utilisateur) {
    this.utilisateur = utilisateur;
  }

}
